### PR TITLE
GraphQL Interface proposal

### PR DESCRIPTION
**Pull request by NoamDev**
This is a proposed interface to allow performing GraphQL queries in DeBots.
I haven't added examples yet, because I wanted to hear some feedback first.

### CODE REVIEW

**Comment by Keshoid** [comment]
Good idea! We definitely need such kind of interface. Now we have Json interface which allows to deserialize graphQL result to structure. But some improvements are needed.

**Comment by NoamDev** [comment]
> Good idea! We definitely need such kind of interface. Now we have Json interface which allows to deserialize graphQL result to structure. But some improvements are needed.

@Keshoid can you elaborate?

**Comment by Keshoid** [comment]
Yes, we plan to improve such an interface.

**Comment by NoamDev** [comment]
@Keshoid hey Nikita, could you give me some feedback on what should be improved in this interface?

**Pull request closed without merging**
