### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by Keshoid**

### CODE REVIEW

**Comment by mikhailUshakoff** [comment]
now you can't compile DeBot with compile greater than 0.47.0

**Review by mikhailUshakoff — CHANGES_REQUESTED** [review]
now you can't compile DeBot with compile greater than 0.47.0

**Comment by Keshoid** [comment]
> now you can't compile DeBot with compile greater than 0.47.0

What do you mean? `>=` in solidity pragma?

**Comment by BigRoma** [comment]
@Keshoid Please, resolve conflicts, before the merge.

**Comment by mikhailUshakoff** [comment]
> > now you can't compile DeBot with compile greater than 0.47.0
> 
> What do you mean? `>=` in solidity pragma?

yep, something like:
`pragma ton-solidity <=0.47.0;` or `pragma ton-solidity ==0.47.0;`

**Comment by ilyar** [comment]
@Keshoid up

**Pull request closed without merging**
